### ISSUE TITLE
CMake Error in build step for'qt5' (Openssl)

### ISSUE THREAD

**Issue by 00aixxia00** [BALL-Project/ball_contrib#17] opened 2018-01-11 09:13 UTC
make[2]: *** [CMakeFiles/qt5.dir/build.make:111: src/qt5-stamp/qt5-build] Fehler 1
make[1]: *** [CMakeFiles/Makefile2:366: CMakeFiles/qt5.dir/all] Fehler 2
make: *** [Makefile:84: all] Fehler 2

if i'm looking for the error in my ball_contrib/build/src/qt5-stamp/qt5-build-*.log, every error is about openssl. Im suggesting its using the new openssl version but the compiler needs the old one.
I'm using Arch Linux.

I'd be very thankfull for help.

**Comment by tkemmer** [comment] 2018-01-11 14:09
Please provide the actual error message or log (qt5-build-error.log) involving openssl.

**Comment by philthiel** [comment] 2018-03-06 14:58
The problem is most likely that you have installed an OpenSSL version >= 1.1,
which is first supported by Qt versions >= 5.10.

If you need that, you can test the branch work/openssl which also uses most recent Qt 5.10.1

**Comment by philthiel** [comment] 2018-03-27 07:55
If you try the current master branch this issue should be fixed as Qt 5.10.1 is included now.

**Closed as completed by philthiel** 2018-03-27 07:55 UTC
Labels: need info
